#!/usr/bin/env sh

# Custom Desktop Installer, scripts to install the metapackages for Custom Desktop.
# Copyright (C) 2022  Natan Junges <natanajunges@gmail.com>
#
# Custom Desktop Installer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Custom Desktop Installer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Custom Desktop Installer.  If not, see <https://www.gnu.org/licenses/>.

. ../common/dialog.sh

clear
op=$(dialog_title Operation; dialog_menu "Choose the desired operation:" 1 "Add repositories and install" 2 "Change icon and cursor theme and favorite apps" 3 "Apply changes (per user)" 4 "Purge unused packages")
err=$?
clear

if [ $err != 0 ]; then
    exit 1
fi

case $op in
    1)
        dialog_title "Add repositories and install - Full package"; dialog_yesno "Install full package?"
        err=$?
        clear
        dialog_title "Adding repositories and installing..."

        if [ $err = 0 ]; then
            ./step-1.sh --full || exit 2
        else
            ./step-1.sh || exit 3
        fi

        echo Logout and login into the GNOME session
    ;;
    2)
        dialog_title "Changing icon and cursor theme and favorite apps..."
        ./step-2.sh || exit 4
    ;;
    3)
        dialog_title "Apply changes - Preserve favorite apps"; dialog_yesno "Preserve favorite apps layout?"
        err=$?
        clear
        dialog_title "Applying changes..."

        if [ $err = 0 ]; then
            ./step-3.sh --preserve || exit 5
        else
            ./step-3.sh || exit 6
        fi
    ;;
    4)
        dialog_title "Purge unused packages - Full package"; dialog_yesno "Purge from full package?"
        err=$?
        clear
        dialog_title "Purging packages..."

        if [ $err = 0 ]; then
            ./step-4.sh --full || exit 7
        else
            ./step-4.sh || exit 8
        fi

        clear
        nano ./build/suggested || exit 9
        dialog_title "Purging unused suggested packages..."
        wait_prompt
        ../common/purge.sh < ./build/suggested || exit 10
        echo Restart your machine
    ;;
esac
